### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME error

### ISSUE THREAD

**Issue by davidejones** [fenneclab/hugo-bin#122]
**hugo-bin:** 0.86.0
**Yarn:** 3.2.1
**Node:** 14.9.0 or 14.9.3
**OS:** Ubuntu 22.04 LTS
**Kernel:** 5.10.104-linuxkit

Getting an error on hugo-bin installs on linux same versions working on mac.

```
root@82f1295a63ad:/app# yarn install --immutable
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 413ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 380ms
➤ YN0000: ┌ Link step
➤ YN0007: │ hugo-bin@npm:0.86.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never has been before or the last one failed
➤ YN0007: │ aws-sdk@npm:2.1012.0 must be built because it never has been before or the last one failed
➤ YN0007: │ puppeteer@npm:1.20.0 must be built because it never has been before or the last one failed
➤ YN0007: │ cpu-features@npm:0.0.3 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.7.0 must be built because it never has been before or the last one failed
➤ YN0009: │ cpu-features@npm:0.0.3 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-e3e820d7/build.log)
➤ YN0009: │ hugo-bin@npm:0.86.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-cc2d68e3/build.log)
➤ YN0007: │ docs@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ ssh2@npm:1.8.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3m 13s
➤ YN0000: Failed with errors in 3m 16s
```

Contents of /tmp/xfs-cc2d68e3/build.log

```bash
# This file contains the result of Yarn building a package (hugo-bin@npm:0.86.0)
# Script name: postinstall

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:750:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

Using node v16.15.1 on the same setup installed fine.

Possibly the imports with `node:path` etc. causing this? taken from https://stackoverflow.com/a/70057245

**Comment by XhmikosR** [comment]
The CI is passing on Ubuntu 22.04 so something else is wrong in your case, unfortunately.

**Comment by davidejones** [comment]
> The CI is passing on Ubuntu 22.04 so something else is wrong in your case, unfortunately.

It is a node version in combination with your package code running on linux not just the OS version. Your CI is using a version of node that works in this case

My original post specifies the versions
>hugo-bin: 0.86.0
Yarn: 3.2.1
Node: 14.9.0 or 14.9.3
OS: Ubuntu 22.04 LTS
Kernel: 5.10.104-linuxkit

I'm using a newer node version now (like your CI) so its not a problem but I just thought I'd highlight it in case you wanted to improve compatibility.  Feel free to close this though if this isn't something you plan to work on.
