### ISSUE TITLE
thowing errors - "unknown shorthand flag"

### ISSUE THREAD

**Issue by dkebler** [fenneclab/hugo-bin#6]
Firstly, Thanks for putting this together, makes it way easier to include hugo using npm install instead of forcing users to manually install separately to their OS. thumbs way up.

Now the issue.  The command I am passing throws an error and yet when I open a terminal and run the same command from there it's no problem.

Here is my code.

````
let exec = require('child_process').execFile;
let hugo = require('hugo-bin');


module.exports= function (data){

// TODO Make command line build utility to build commands.
let cmd = '-v'
  			+ ' --config="'   		+ data.repoPath + data.dir.content + data.html.template	+ 'config.toml' + '"'
				+ ' --baseUrl="'			+ data.build.url + ':'+ data.build.port				+'"'
  			+ ' --layoutDir="'			+ data.repoPath + data.dir.html + data.html.template + data.html.layouts +'"'
				+ ' --contentDir="'	  + data.repoPath + data.dir.content + data.html.template + "pages/"							+'"'
  			+ ' --destination="'	+ data.repoPath + data.dir[data.build.type] 							+'"'
			;
Debug.L1('cmd: ' + cmd);

exec(hugo, [cmd], (err, stdout) => {
			  console.log(stdout);
				console.log(err);
			});
```

below  is the error.  If I copy and paste the cmd: from the dumped object into a terminal it runs fine generating the site with no error about "unknown shorthand flag"  so it's not the syntax nor paths in the command itself causing the error.

I'm using node 6.5 on an Ubuntu 14.04 machine, with your 0.3 version

```
{ Error: Command failed: /mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/node_modules/hugo-bin/vendor/hugo -v --config="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/content/hugo/config.toml" --baseUrl="http://localhost:8090" --layoutDir="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/assets/html/hugo/layouts/" --contentDir="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/content/hugo/pages/" --destination="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/builds/dev/"
Error: unknown shorthand flag: ' ' in - --config="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/content/hugo/config.toml" --baseUrl="http://localhost:8090" --layoutDir="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/assets/html/hugo/layouts/" --contentDir="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/content/hugo/pages/" --destination="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/builds/dev/"

  at ChildProcess.exithandler (child_process.js:206:12)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Socket.<anonymous> (internal/child_process.js:334:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)

  killed: false,
  code: 255,
  signal: null,
  cmd: '/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/node_modules/hugo-bin/vendor/hugo -v --config="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/content/hugo/config.toml" --baseUrl="http://localhost:8090" --layoutDir="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/assets/html/hugo/layouts/" --contentDir="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/content/hugo/pages/" --destination="/mnt/AllData/hacking/active-dev-repos/Super-Static-Site-Starter/builds/dev/"' }
```

**Comment by dkebler** [comment]
Well, instead of using your child process call I went back to the promise based version I was using the error has gone away.  You might take a look at that...maybe in 6.5 `let exec = require('child_process').execFile;`  causes a problem and needs to be just .exec?  or something else...

So FYI here is my promise based version.
`````
let exec = require('child-process-promise').exec;
let hugo = require('hugo-bin');


module.exports= function (data){

// TODO Make command line build utility to build commands.
let cmd = hugo + ' -v'
  			+ ' --config="'   		+ data.repoPath + data.dir.content + data.html.template	+ 'config.toml' + '"'
				+ ' --baseUrl="'			+ data.build.url + ':'+ data.build.port				+'"'
  			+ ' --layoutDir="'			+ data.repoPath + data.dir.html + data.html.template + data.html.layouts +'"'
				+ ' --contentDir="'	  + data.repoPath + data.dir.content + data.html.template + "pages/"							+'"'
  			+ ' --destination="'	+ data.repoPath + data.dir[data.build.type] 							+'"'
			;
Debug.L1('cmd: ' + cmd);

return exec(cmd)
.then(function (result) {
	let stdout = result.stdout;
	let stderr = result.stderr;
	Debug.L1('Hugo says: ', stdout);
	Debug.L1('stderr: ', stderr);
	console.log("done with hugo command")
 });

}
```

**Comment by satoshun00** [comment]
@dkebler 
Thunk you for reporting 😄 

Your first `child_process.execFile` example has invalid argument for `args`.
see: https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

That should be,

```
let exec = require('child_process').execFile;
let hugo = require('hugo-bin');

exec(hugo, [
  '-v',
  '--config', data.repoPath + data.dir.content + data.html.template + 'config.toml',
  '--baseUrl', data.build.url + ':' + data.build.port
  // and more
], (err, stdout) => {
  console.log(stdout);
  console.log(err);
});
```
