### ISSUE TITLE
Error when building in Docker container

### ISSUE THREAD

**Issue by shauntarves** [fenneclab/hugo-bin#88]
I am trying to build a Docker image of a node project that uses this package.

My Dockerfile
```
FROM node as build-stage
WORKDIR /app
COPY package.json /app/
RUN npm install --silent
COPY ./ /app/
RUN npm run build
```

I get this bizarre error when using `from node` and a DIFFERENT error using `node-alpine`

`node`
```
> temp@0.0.1 build:hugo /app
> hugo -d ../dist -s site -v

/app/node_modules/hugo-bin/vendor/hugo: 1: /app/node_modules/hugo-bin/vendor/hugo: ����: not found
/app/node_modules/hugo-bin/vendor/hugo: 2: /app/node_modules/hugo-bin/vendor/hugo: Syntax error: "(" unexpected
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! temp@0.0.1 build:hugo: `hugo -d ../dist -s site -v`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the temp@0.0.1 build:hugo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T21_36_31_808Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! temp@0.0.1 build: `npm run build:webpack && npm run build:hugo`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the temp@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T21_36_31_824Z-debug.log
```

`node-alpine`
```
> temp@0.0.1 build:hugo /app
> hugo -d ../dist -s site -v

internal/child_process.js:372
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (internal/child_process.js:372:11)
    at spawn (child_process.js:559:9)
    at Object.<anonymous> (/app/node_modules/hugo-bin/cli.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temp@0.0.1 build:hugo: `hugo -d ../dist -s site -v`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the temp@0.0.1 build:hugo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T21_41_51_867Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temp@0.0.1 build: `npm run build:webpack && npm run build:hugo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the box-office@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T21_41_51_889Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by shauntarves** [comment]
Solved. The problem was that the local `node_modules` folder was being copied into the Docker container so it was getting my MacOS executable for the vendor/hugo file!

**Comment by XhmikosR** [comment]
@shauntarves you can close this then.
